### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by woelffer** [woelffer/gamedemo#4]
- [ ] Level Design - implement multiple levels for enemy spawns and functionality
- [x] Enemy projectiles
- [x] Enemy animation 
- [ ] Player abilities -  shield, phase shift, missile(aim with mouse), Scatter Shot
- [ ] Create Save Files for player score records and player upgrades
- [ ] Items - Speed Buff, Shield Buff, Shift Attack Buff(phase shift destroys enemies)
- [ ] Boss Design - Multiple Bosses that have animation indicators for strikes for player fairness.
- [x] Title Screen
- [x] Visual and Auditory signal for player death
- [ ] Streamline main file to increase modularity
- [ ] Prevent enemies to overlap each other during spawn or gameplay
- [ ] *Multiplayer*
